plugins {
    id 'fabric-loom' version '1.14.10' apply false
}

allprojects {
    group = providers.gradleProperty('maven_group').get()
    version = providers.gradleProperty('mod_version').get()
}

configure(subprojects.findAll { it.path.startsWith(':versions:Fabric-1.21.') }) {
    apply from: rootProject.file('1.21-shared/build.gradle')
}
